// component
export const COMPONENT_MOVEMENT_VERTICAL_DRAG = 0.01;
export const COMPONENT_MOVEMENT_VERTICAL_MAX_VELOCITY = 200;
export const COMPONENT_MOVEMENT_HORIZONTAL_DRAG = 0.01;
export const COMPONENT_MOVEMENT_HORIZONTAL_MAX_VELOCITY = 200;

// player
export const PLAYER_MOVEMENT_HORIZONTAL_VELOCITY = 20;
export const PLAYER_MOVEMENT_VERTICAL_VELOCITY = 20;
export const PLAYER_BULLET_MAX_COUNT = 10;
export const PLAYER_BULLET_INTERVAL = 300;
export const PLAYER_BULLET_SPEED = 300;
export const PLAYER_BULLET_LIFESPAN = 3;

// enemy
export const ENEMY_SCOUT_MOVEMENT_VERTICAL_VELOCITY = 10;
export const ENEMY_SCOUT_MOVEMENT_HORIZONTAL_VELOCITY = 7;
export const ENEMY_SCOUT_MOVEMENT_MAX_X = 80;

export const ENEMY_FIGHTER_MOVEMENT_VERTICAL_VELOCITY = 13;
export const ENEMY_FIGHTER_BULLET_MAX_COUNT = 10;
export const ENEMY_FIGHTER_BULLET_INTERVAL = 2000;
export const ENEMY_FIGHTER_BULLET_SPEED = -280;
export const ENEMY_FIGHTER_BULLET_LIFESPAN = 3;
